postgres:
  container_name: postgres
  restart: always
  image: postgres:latest
  environment:
  - POSTGRES_USER=user
  - POSTGRES_PASSWORD=asdQWE123
  volumes:
  - ./postgres-data:/var/lib/postgresql
  ports:
    - 5432:5432